[package]
name = "dtw"
version = "0.1.0"
edition = "2021"
resolver = "2"

[dependencies]
ndarray = "0.15.6"

[dev-dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
ndarray = { version = "0.15.6", features = ["serde"] }
